# Generated by Django 6.0.3 on 2026-04-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_pedido_direccion_envio_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20, verbose_name='Estado del Pago'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='transaccion_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Transacción'),
        ),
    ]
