# Generated by Django 6.0.3 on 2026-04-14 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_pedido_estado_pago_pedido_transaccion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='El precio debe ser mayor a 0')], verbose_name='Precio'),
        ),
    ]
